### ISSUE TITLE
Japanese can not be entered on iPad Pro

### ISSUE THREAD

**Issue by hidao80** [yymm/locks#3]
I can enter double-byte symbols from the software keyboard. But inline conversion is not possible. When I type it half-width alphanumeric characters will be entered. Even using bluetooth keyboard was not improved.

Environment: 
- Hardware
  - iPad Pro 10.5 (MODEL MQDW2J/A)
- OS
  - iOS 11.2
- browser
  - Chrome ver. 63.0.3239.73
  - Safari ver. unkown

thanks.

**Comment by yymm** [comment]
I tried it with my ios terminal, and the same phenomenon was reproduced.

It seems that it is unresolved at Issue of CodeMirror ↓

https://github.com/codemirror/CodeMirror/issues/3137

~~Unless this Issue is resolved, it is difficult for the application side to deal with it.~~

~~Please wait a little more, thanks.~~

Please see latest comment.

**Comment by yymm** [comment]
I tried https://qiita.com/ttakuru88/items/e363267772cacf4c1fa2 and it was resolve! (also deploy done.)

- https://github.com/yymm/locks/commit/8350c1ebf5fa04abf540e383c7281f6399c33e21
- https://github.com/yymm/locks/commit/46f13c976b50c2c83badae4252512fb23556283d

I confirmed with my iPhone5 and iPad (Safari and Chrome).

Please check whether it has been fixed.

If you can check this Issue will close.

**Comment by hidao80** [comment]
it is perfect! 

Japanese input / conversion is now possible on my ipad! thank you very much!

Confirmed:

- hardwarw
  - iPad Pro 10.5
- OS
  - iOS 11.2
- Web browser
  - Safari
  - Chrome
- Keybord
  - Default soft keybored
